Traceback (most recent call last):
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/icdc/Documents/NFDI/Kemeng/myenv/venvBook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
file_tsProfile = glob(os.path.join(os.getcwd(), "dsg_tsProfile", "*.nc"))
file_tsProfile
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 1[0m
[0;32m----> 1[0m file_tsProfile [38;5;241m=[39m [43mglob[49m(os[38;5;241m.[39mpath[38;5;241m.[39mjoin(os[38;5;241m.[39mgetcwd(), [38;5;124m"[39m[38;5;124mdsg_tsProfile[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m*.nc[39m[38;5;124m"[39m))
[1;32m      2[0m file_tsProfile

[0;31mNameError[0m: name 'glob' is not defined

